version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cmpassword
      POSTGRES_DB: chonkymammoth
    ports:
      - "5432:5432"
    volumes:
      - cm_postgres_data:/var/lib/postgresql/data
      # Uncomment to use initialization scripts
      # - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  cm_postgres_data:
